# Generated by Django 3.2.9 on 2021-12-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='project name')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='project description')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='media')),
                ('completed', models.BooleanField(default=False, verbose_name='Is this project compleated')),
                ('team', models.TextField(blank=True, default='[]', null=True, verbose_name='Team members')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
