# Generated by Django 4.0.4 on 2023-02-25 17:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('organizer', models.CharField(default='CLUB FLUX', max_length=50, verbose_name='Event Organizer')),
                ('team', models.TextField(blank=True, default='[]', null=True, verbose_name='Team members')),
                ('poster', models.ImageField(blank=True, default='', null=True, upload_to='media')),
                ('faculty', models.TextField(blank=True, default='[]', null=True, verbose_name='Faculty members')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50, verbose_name='Image heading')),
                ('description', models.CharField(max_length=100, verbose_name='Image description')),
                ('image', models.ImageField(default='', upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='project description')),
                ('start_year', models.CharField(blank=True, max_length=10, null=True, verbose_name='project start year')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='project category')),
                ('image1', models.ImageField(blank=True, default='', null=True, upload_to='media')),
                ('image2', models.ImageField(blank=True, default=False, null=True, upload_to='media')),
                ('image3', models.ImageField(blank=True, default=False, null=True, upload_to='media')),
                ('completed', models.BooleanField(default=False, verbose_name='Is this project compleated')),
                ('team', models.TextField(blank=True, default='[]', null=True, verbose_name='Team members')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Added')),
            ],
            options={
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Member Name')),
                ('scholar_no', models.CharField(blank=True, max_length=10, null=True)),
                ('enrollment_no', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Student email')),
                ('year', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=50)),
                ('scholar_no', models.CharField(blank=True, max_length=10, null=True)),
                ('enrollment_no', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flux.events')),
            ],
            options={
                'verbose_name_plural': 'All Registrations',
            },
        ),
    ]
