# Generated by Django 3.2.9 on 2021-12-23 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('organizer', models.CharField(default='CLUB FLUX', max_length=50, verbose_name='Event Organizer')),
                ('team', models.TextField(blank=True, default='[]', null=True, verbose_name='Team members')),
                ('faculty', models.TextField(blank=True, default='[]', null=True, verbose_name='Faculty members')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50, verbose_name='Image heading')),
                ('description', models.CharField(max_length=100, verbose_name='Image description')),
                ('image', models.ImageField(default='', upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Member Name')),
                ('scholar_no', models.CharField(blank=True, max_length=10, null=True)),
                ('enrollment_no', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Project Name'),
        ),
        migrations.CreateModel(
            name='Registraion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('year', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=50)),
                ('scholar_no', models.CharField(blank=True, max_length=10, null=True)),
                ('enrollment_no', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flux.events')),
            ],
            options={
                'verbose_name_plural': 'All Registrations',
            },
        ),
    ]
