# Generated by Django 3.2.9 on 2021-12-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0005_auto_20211223_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image2',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image3',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='media'),
        ),
    ]
