# Generated by Django 3.2.9 on 2021-12-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0006_auto_20211223_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image2',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image3',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='media'),
        ),
    ]
