# Generated by Django 3.2.9 on 2021-12-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0009_auto_20211224_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registraion',
            new_name='Registration',
        ),
    ]
