# Generated by Django 3.2.9 on 2021-12-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0007_auto_20211223_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='registraion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Student email'),
        ),
    ]
